# test, build, package and deploy stages.

image: docker:latest
services:
  - docker:dind


stages:
  - test
  - build
  - package
  - deploy
  - package-frontend
  - deploy-frontend


test:
  stage: test
  tags:
    - deployment
  image: maven:3.8.5-openjdk-17
  script:
    - pwd
    - echo $BACKEND_DIR
    - cd $BACKEND_DIR
    - mvn -version
    - mvn clean test -Dspring.profiles.active=prod
  only:
    - main


build:
  stage: build
  tags:
    - deployment
  image: maven:3.8.5-openjdk-17
  script:
    - pwd
    - cd $BACKEND_DIR
    - mvn clean package -Dspring.profiles.active=prod
  artifacts:
    paths:
      - $BACKEND_DIR/target/*.jar
  only:
    - main


package:
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  stage: package
  tags:
    - deployment
  script:
    - pwd
    - ls -la PharmaConnect-Backend/pharma/target/
    - docker build -t docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA $BACKEND_DIR
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
    - docker push docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA
  only:
    - main


deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f my-app || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8073:8080 --name my-app docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA"
  environment:
    name: production
    url: http://172.17.3.127:8073
  only:
    - main

package-frontend:
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  stage: package-frontend
  tags:
    - deployment
  script:
    - pwd
    - ls -la PharmaConnect-Frontend/
    - docker build -t docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA-frontend $FRONTEND_DIR
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
    - docker push docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA-frontend
  only:
    - main

deploy-frontend:
  stage: deploy-frontend
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA-frontend"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f frontend-app || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8074:4200 --name frontend-app docker.io/rameezparkar23/pharmaconnect:$CI_COMMIT_SHORT_SHA-frontend"
  environment:
    name: production-frontend
    url: http://172.17.3.127:8074
  only:
    - main
