use `CSCI5308_9_DEVINT`;

-- user information
CREATE TABLE `USERS`(
  `USER_ID` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `BIRTH_DATE` VARCHAR(20) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `EMAIN_ID` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `GENDER` VARCHAR(10)
);

-- login information
CREATE TABLE `LOGIN` (
    `Login_ID` INT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` INT,
    `Login_Time` DATETIME,
    `Status` BOOLEAN,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- drug informaiton
CREATE TABLE `DRUGS` (
  `DRUG_ID` INT PRIMARY KEY AUTO_INCREMENT,
  `DRUG_NAME` VARCHAR(50) NOT NULL,
  `TYPE` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(20) NOT NULL,
  `UNIT_PRICE` double NOT NULL,
  `SELLING_PRICE` double NOT NULL,
  `COMPANY_NAME` VARCHAR(50) NOT NULL,
  `PRODUCTION_DATE` date NOT NULL,
  `EXPIRATION_DATE` date NOT NULL,
  `QUANTITY` INT  NOT NULL,
  `PRESCRIPTION` boolean NOT NULL
) ;

-- cotntain purchase history of a store
CREATE TABLE `PURCHASES` (
  `PURCHASE_ID` INT PRIMARY KEY AUTO_INCREMENT,
  `CODE` varchar(20) NOT NULL,
  `DRUG_NAME` varchar(50) NOT NULL,
  `TYPE` varchar(20) NOT NULL,
  `COMPANY_NAME` varchar(20) NOT NULL,
  `QUANTITY` int(11) NOT NULL,
  `PRICE` double NOT NULL,
  `TOTAL_AMOUNT` double NOT NULL
);

-- Inventory of a store
CREATE TABLE `STOCKS` (
  `DRUG_ID` INT ,
  `DRUG_NAME` VARCHAR(50) NOT NULL,
  `TYPE` VARCHAR(10) NOT NULL,
  `AVAILABLE_QUANTITY` INT NOT NULL,
  `STORE` VARCHAR(50) NOT NULL
);

-- Store details
CREATE TABLE `STORE`(
  `STORE_ID` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `STORE_NAME` VARCHAR(50) NOT NULL,
  `EMAIL_ID` VARCHAR(50) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL
);


-- Store location information
CREATE TABLE `LOCATION`(
  `LOCATION_ID` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `STORE_ID` INT,
  `ADDRESS_LINE1` VARCHAR(50) NOT NULL,
  `ADDRESS_LINE2` VARCHAR(50),
  `CITY` VARCHAR(50) NOT NULL,
  `STATE` VARCHAR(50) NOT NULL,
  `COUNTRY` VARCHAR(50) NOT NULL,
  `POSTCODE` VARCHAR(20) NOT NULL,
   FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);


-- Drug price iformation, maintain by store
create table `DRUG_STORE_PRICE`
(
	`DRUG_ID` INT,
    `DRUG_NAME` VARCHAR(50),
    `CODE` VARCHAR(20),
	`STORE_ID` INT,
    `STORE_NAME` VARCHAR(50) NOT NULL,
    `UNIT_PRICE` double,
    `SELLING_PRICE` double,
    `QUANTITY` INT
);

-- Admin 
CREATE TABLE `ADMIN`(
  `ADMIN_ID` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `ADMIN_NAME` VARCHAR(50) NOT NULL,
  `EMAIL_ID` VARCHAR(50) NOT NULL,
  `BIRTH_DATE` VARCHAR(20) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL
);


